plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.smartpantry'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.smartpantry"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
}
